FROM python:3.10-slim

# cd to folder
WORKDIR /gateway_service

# setup file
COPY gateway_service/ .

# Copy requirements first to leverage Docker cache
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the app runs on
EXPOSE 80

# Command to run the application
CMD ["python", "main.py"]

# Build command:
# docker build -t gateway_service . -f Dockerfile.gateway

# Run command:
# docker run -it --name gateway_service --net camera_track_network -v D:\camera\data\demo\gateway_service:/gateway_service -p 80:80 gateway_service