FROM camera_track_env

# cd to folder
WORKDIR /recognition_service

# setup file
COPY recognition_service/ .

# install requirement
RUN pip install --no-cache-dir -r requirements.txt

# start app
# CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 8002 --reload"]
CMD ["python3", "main.py"]

### build vector db
# build docker image
## docker pull chromadb/chroma

# build and run
## docker run -it --name vector_db_service --net camera_track_network -v D:\camera\chromadb:/chroma/chroma -p 8000:8000 chromadb/chroma

### build this service
# build docker image
## docker build -t recognition . -f Dockerfile.recognition

# build and run
## docker run --gpus all -it --name recognition_service --net camera_track_network -v D:\camera\data\demo\recognition_service:/recognition_service -p 8002:8002 recognition
